build:
  environment:
    php:
      version: 7.4
  nodes:
    analysis:
      dependencies:
        before:
        - git clone https://github.com/WoltLab/WCF.git wcf/
        - git clone https://github.com/Teralios/de.teralios.validator.quiz.git teralios/
        - cd wcf/
        - git checkout 5.3
        - cd ..
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis
          - eslint-run "ts/**"
filter:
  excluded_paths:
    - "*.build.js"
    - "*.min.js"
    - "files/js/*"
  dependency_paths:
    - wcf/
    - teralios/