build:
        environment:
          php:
            version: 7.4
        nodes:
          analysis:
            dependencies:
              before:
                - git clone https://github.com/WoltLab/WCF.git wcf/
            tests:
              override:
                - php-scrutinizer-run
filter:
  dependency_paths:
    - wcf/