build:
  environment:
    php:
      version: 7.4
  nodes:
    analysis:
      filter:
        dependency_paths:
          - wcf/
      dependencies:
        before:
          - git clone https://github.com/WoltLab/WCF.git wcf/
      tests:
        override:
          - php-scrutinizer-run