ALTER TABLE wcf1_user ADD COLUMN quizPlayed INT(10) NOT NULL DEFAULT 0;
ALTER TABLE wcf1_user ADD COLUMN quizMaxScore SMALLINT(4) NOT NULL DEFAULT 0;
ALTER TABLE wcf1_user ADD COLUMN quizPlayedUnique INT(10) NOT NULL DEFAULT 0;