name: PHP Code Style

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  php:
    name: Run PHP CodeSniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chekalsky/phpcs-action@v1
